edition = 1
exports = []

[package]
name = "echo-client"
description = "Echo Client Example"

[package.actr_type]
manufacturer = "acme"
name = "echo-client-app"

[dependencies]
echo-echo-server = { actr_type = "acme+EchoService" }
echo-twice-server = { actr_type = "acme+EchoTwiceService" }

[system.signaling]
url = "wss://actrix1.develenv.com/signaling/ws"

[system.deployment]
realm_id = 2368266035

[system.discovery]
visible = true

[system.webrtc]
force_relay = false
stun_urls = ["stun:actrix1.develenv.com:3478"]
turn_urls = ["turn:actrix1.develenv.com:3478"]

[acl]

[[acl.rules]]
permission = "allow"
types = ["acme+EchoService", "acme+EchoTwiceService"]
